networks:
  fabric_test:
    name: fabric_test
    driver: bridge

services:
  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:latest
    ports:
      - 7050:7050
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/orderer
      # - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      # - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      # - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/orderer/msp
    volumes:
      - ./config/orderer-org/orderer.yaml:/etc/hyperledger/orderer/orderer.yaml
      - ./config/orderer-org/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/etc/hyperledger/orderer/msp
      - ./config/channel-artefacts/genesisblock:/etc/hyperledger/orderer/genesisblock:ro
      - ./config/orderer-org/ordererOrganizations/example.com/tlsca:/etc/hyperledger/tlsca:ro
      # - ./config/orderer-org/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt:/etc/hyperledger/orderer/tls/server.crt:ro
    networks:
      - fabric_test


  # peer0.org1.example.com:
  #   container_name: peer0.org1.example.com
  #   image: hyperledger/fabric-peer:latest
  #   environment:
  #     - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
  #     - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
  #     - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
  #     - CORE_PEER_ID=peer0.org1.example.com
  #     - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
  #     - CORE_PEER_LOCALMSPID=Org1MSP
  #     - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peercfg/msp
  #     - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9443
  #   volumes:
  #     - ./config/org1:/etc/hyperledger/peercfg
  #     - ./config/crypto/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/peercfg/msp
  #     - /var/run/docker.sock:/host/var/run/docker.sock
  #   networks:
  #     - fabric_test
  #   depends_on:
  #     - orderer.example.com

  # peer0.org2.example.com:
  #   container_name: peer0.org2.example.com
  #   image: hyperledger/fabric-peer:latest
  #   labels:
  #     service: hyperledger-fabric
  #   environment:
  #     - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
  #     - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
  #     - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
  #   volumes:
  #     - ./config/org2:/etc/hyperledger/peercfg
  #     - /var/run/docker.sock:/host/var/run/docker.sock
