Organizations:
  - Name: Org1
    Domain: org1.example.com
    Config: non_existant_path/core.yaml
    Crypto_path: non_existant_path/crypto-config
    Docker_path: non_existant_path/Dockerfile

  - Name: Org2
    Domain: org2.example.com
    Config: non_existant_path/core.yaml
    Crypto_path: non_existant_path/crypto-config
    Docker_path: non_existant_path/Dockerfile

Orderer:
  - Name: Orderer
    Domain: example.com
    Config: non_existant_path/orderer.yaml
    Crypto_path: non_existant_path/crypto-config